opensearch-project/search-relevance

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/model/builder/SearchRequestBuilder.java
src/test/java/org/opensearch/searchrelevance/model/builder/SearchRequestBuilderTests.java

Change search request builder logics to take all possible fields, includes aggregation, includes, .. previous implementation only took query, _source and search_pipeline. 
This implementation handles the 'query' field separately from other fields because:
1. Custom query types (like hybrid, neural) are not registered in the default QueryBuilders
2. Using WrapperQuery allows passing through any query structure without parsing
3. All other fields (aggregations, source filtering, etc.) can be parsed normally by SearchSourceBuilder
**Testing**
- verified the changes with a aggregation query 
```
{
"size": 20,
"query": {
"multi_match": {
"query": "apple pie",
"fields": ["name", "description"]
}
},
"aggs": {
"price_stats": {
"stats": {
"field": "price"
}
},
"price_ranges": {
"range": {
"field": …
```

build search request with normal parsing and wrapper query

---

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/experiment/EmptyExperimentOptions.java
src/main/java/org/opensearch/searchrelevance/experiment/ExperimentOptions.java
src/main/java/org/opensearch/searchrelevance/experiment/ExperimentOptionsFactory.java
src/main/java/org/opensearch/searchrelevance/experiment/ExperimentOptionsForHybridSearch.java
src/main/java/org/opensearch/searchrelevance/experiment/QuerySourceUtil.java
src/main/java/org/opensearch/searchrelevance/experiment/SubExperimentHybridSearchDao.java
src/main/java/org/opensearch/searchrelevance/metrics/MetricsHelper.java
src/main/java/org/opensearch/searchrelevance/model/builder/SearchRequestBuilder.java
src/main/java/org/opensearch/searchrelevance/transport/experiment/PutExperimentTransportAction.java
src/test/java/org/opensearch/searchrelevance/experiment/ExperimentOptionsFactoryTests.java
src/test/java/org/opensearch/searchrelevance/experiment/QuerySourceUtilTests.java
src/test/java/org/opensearch/searchrelevance/model/builder/SearchRequestBuilderTests.java

Adding building blocks for hybrid optimizer: 
- extend Experiments API by allowing different experiment options
- hardcoded experiment options for initial release (3.1 scope)
- validate that query in search configuration does not have temporary pipeline in it
- if experiment is of type hybrid search then we iterate over experiment options, create temp search pipeline for each unique combination of parameters
I'm extending existing Experiment API, this is how request for hybrid search experiment will look like:
```
PUT _plugins/search_relevance/experiments
{
"querySetId": "70a624f6-53c9-4644-8af8-6b76485379e1",
"searchConfigurationList": ["7d0dd57f-aa14-4620-ab17-944779581225", "614b0347-8e10-4f10-b632-f0d43a79f572"],
"size": 2,
"judgmentList": ["4a01b588-d8f8-476d-8b78-4485767fc7cd"], …
```

Hybrid optimizer - added experiment options for hybrid search

---

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/experiment/QuerySourceUtil.java
src/main/java/org/opensearch/searchrelevance/model/builder/SearchRequestBuilder.java
src/test/java/org/opensearch/searchrelevance/experiment/QuerySourceUtilTests.java
src/test/java/org/opensearch/searchrelevance/model/builder/SearchRequestBuilderTests.java

Added validation of the query type for Hybrid Search Optimizer. 
Parameters that are validated:
- query must be of type "hybrid"
- query must have exactly two sub-queries. this is needed because we did not logic for distributing weights for more then 2 sub-queries, and having one or zero sub-queries does not have a lot of sense (it equivalent of running sub-query as a standalone query).
I'm checking basic things based on general query structure,  more deep checks are limited without direct dependency on hybrid query classes. Adding such dependency is problematic because neural-search repo does not publish jar archives, only zip files that are harder to adopt as runtime dependency.
https://github.com/o19s/search-relevance/issues/115
By submitting this pull request, I confirm that my …

Added validation for hybrid query structure

---

build.gradle
src/main/java/org/opensearch/searchrelevance/settings/SearchRelevanceSettings.java
src/test/java/org/opensearch/searchrelevance/plugin/SearchRelevancePluginTests.java

We added a feature flag for SRW in https://github.com/opensearch-project/search-relevance/pull/34, it's enabled by default. We need to flip the default value to false/disabled, main reason being - we not going to meet the 3.1 release time window with application security review. 
Don't merge it yet without corresponding change in UI. 
https://github.com/opensearch-project/search-relevance/issues/33

Flipping default feature flag setting to disabled

---

.github/workflows/test_security.yml

Adding CI action to run integ test with security enabled. This is part of the prep for 3.1 release
https://github.com/opensearch-project/search-relevance/issues/58

Adding CI action to run integ tests with security enabled

---

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndices.java
src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManager.java
src/main/java/org/opensearch/searchrelevance/transport/experiment/DeleteExperimentTransportAction.java
src/main/java/org/opensearch/searchrelevance/transport/experiment/GetExperimentTransportAction.java
src/main/java/org/opensearch/searchrelevance/transport/judgment/DeleteJudgmentTransportAction.java
src/main/java/org/opensearch/searchrelevance/transport/judgment/GetJudgmentTransportAction.java
src/main/java/org/opensearch/searchrelevance/transport/queryset/DeleteQuerySetTransportAction.java
src/main/java/org/opensearch/searchrelevance/transport/queryset/GetQuerySetTransportAction.java
src/main/java/org/opensearch/searchrelevance/transport/searchConfiguration/DeleteSearchConfigurationTransportAction.java
src/main/java/org/opensearch/searchrelevance/transport/searchConfiguration/GetSearchConfigurationTransportAction.java
src/test/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesTests.java

Fixed user facing error for scenario when main plugin entities are not yet created. We're checking if index exists and fail in case it doesn't. With this PR logic changes to create index if not present.
Things I have added/changed:
- is_protected flag for index
- framework for running backend action in sync or async modes
- logic that decides between sync/async modes depending on index is_protected flag
- deleted if_index_absent check from Dao classes, this is taken care of by new framework
Flexible logic is needed for protected (aka system) indexes because of special handling of thread context due to usage of secure plugin of OpenSearch.
Continue work of https://github.com/opensearch-project/search-relevance/pull/54, 
https://github.com/opensearch-project/search-relevance/issues/55
By …

Added lazy index creation for APIs

---

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/common/PluginConstants.java
src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManager.java
src/test/data-esci/schema.json
src/test/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManagerTests.java
src/test/scripts/demo.sh
src/test/scripts/demo_hybrid_optimizer.sh

Programmatically set limit of fields for search relevance indexes to 100,000 instead of default 1,000. We need a note in documentation that explains how customer can increase it themselves if this limit is not enough. 
Strip out commands that increase this limit in demo script.
https://github.com/opensearch-project/search-relevance/issues/71

Set limit for number of fields programmatically during index creation

---

src/main/java/org/opensearch/searchrelevance/dao/QuerySetDao.java
src/main/java/org/opensearch/searchrelevance/model/QuerySet.java
src/main/java/org/opensearch/searchrelevance/model/QuerySetEntry.java
src/main/java/org/opensearch/searchrelevance/transport/queryset/PostQuerySetTransportAction.java
src/main/java/org/opensearch/searchrelevance/transport/queryset/PutQuerySetTransportAction.java
src/main/resources/mappings/queryset.json
src/test/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManagerTests.java
src/test/java/org/opensearch/searchrelevance/rest/RestPutQuerySetActionTests.java

Change model for Query Set, new model is model restrictive comparing to "allow all" dynamic mode. 
Fields that are allowed: 
- `queryText` holds the actual test of the user query
Example of query set document with new model:
```
{
"id": "dd49c93b-eefd-4586-9144-e02e43ead6aa",
"name": "query_set",
"description": "Test query set",
"sampling": "manual",
"timestamp": "2025-06-09T19:46:47.172Z",
"querySetQueries": [
{
"queryText": "phone"
},
{
"queryText": "iphone"
},
{
"queryText": "steel"
}
]
}
``` 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBU …

Update query set schema to avoid too many fields issue

---

src/main/resources/mappings/judgment.json
src/main/resources/mappings/queryset.json

Disable indexing for new fields introduced in https://github.com/opensearch-project/search-relevance/pull/87 and https://github.com/opensearch-project/search-relevance/pull/77 for QuerySet and Judgment indexes. This is safe because we're not using those fields in any search queries or aggregations. This should save compute and memory resources because those fields will not be indexed. 

Disabled indexing for some fields in query set and jugments indexes

---

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/dao/JudgmentCacheDao.java
src/main/java/org/opensearch/searchrelevance/dao/QuerySetDao.java
src/main/java/org/opensearch/searchrelevance/dao/SearchConfigurationDao.java
src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManager.java
src/main/java/org/opensearch/searchrelevance/judgments/LlmJudgmentsProcessor.java
src/main/java/org/opensearch/searchrelevance/transport/experiment/PutExperimentTransportAction.java
src/main/java/org/opensearch/searchrelevance/transport/judgment/PutJudgmentTransportAction.java

- change query set, search configuration get to be synchronous. since they're no longer within system indices
- refactor llm judgment processor logics
- update judgment cache upset logics
###Test
- judgment generated
- ingest 8 query text in queryset
- then judgment also should have 8 items in judgmentRating with distinct query value
```
"judgmentRatings":  [
{
"query": "phone",
"ratings":  [
{
"docId": "B07SVZW34Z",
"rating": "1.0" 
},
{
"docId": "B07K73P7NX",
"rating": "0.7" 
},
{
"docId": "B07T99FCD2",
"rating": "0.1" 
},
{
"docId": "B07V5SBP7N",
"rating": "1.0" 
},
{
"docId": "B07CW24XX9",
"rating": "0.0" 
}
]
},
{
"query": "iphone",
"ratings":  [
{
"docId": "B013DDMPXK",
"rating": "1.0" 
},
{
"docId": "B07DBZDT89",
"rating": "0.0" 
},
{
"docId": "B078M6HWX5",
"rating": "0.0" 
},
{ …
```

deduplicate judgmentRatings + change some operations to synchronous

---

build.gradle
src/test/java/org/opensearch/searchrelevance/BaseSearchRelevanceIT.java

We do received autocut for failing tests in distribution pipeline. For non-security tests they are failing because feature flag is not set properly and SRW is disabled. For secure tests error is not clear, adding command similar to other repos.
Fix one issue with failing integration tests, qnd trying to address second:
- enable feature flag as part of test setup
- add task for running on remote cluster
https://github.com/opensearch-project/search-relevance/issues/52
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-o …

Fixed integration tests failures in distribution pipeline

---

src/main/java/org/opensearch/searchrelevance/judgments/UbiJudgmentsProcessor.java

Found a bug in UBI judgment generation, which leads to a failure on pointwise evaluation.
- judgment score found as null due to a name mismatching  
_List any issues this PR will resolve, e.g. Closes [...]._

bug fix for UBI judgment generation

---

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/experiment/ExperimentOptionsForHybridSearch.java
src/main/java/org/opensearch/searchrelevance/experiment/QuerySourceUtil.java
src/test/java/org/opensearch/searchrelevance/action/experiments/ExperimentIT.java
src/test/java/org/opensearch/searchrelevance/experiment/ExperimentOptionsForHybridSearchTests.java
src/test/java/org/opensearch/searchrelevance/experiment/QuerySourceUtilTests.java
src/test/resources/data_esci/CreateIndex.json
src/test/resources/experiment/CreateExperimentHybridOptimizer.json
src/test/resources/searchconfig/CreateSearchConfigurationHybridQuery.json

Missing experiment variants for Hybrid Optimizer caused by floating-point precision errors when incrementing by 0.1 in the for-loop.
With this change we now:
- calculate the exact number of steps needed
- use an integer counter to avoid floating-point accumulation errors
- ensure the maximum value is precisely included by special-casing the last step
https://github.com/opensearch-project/search-relevance/issues/109

Fixed missing variants in Hybrid Optimizer

---

release-notes/opensearch-search-relevance.release-notes-3.1.0.0.md

Release notes must follow https://github.com/opensearch-project/opensearch-plugins/blob/main/RELEASE_NOTES.md

Reformatted release notes according to OS stadard schema

---

CHANGELOG.md
release-notes/opensearch-search-relevance.release-notes-3.1.0.0.md

Manually to the upport of https://github.com/opensearch-project/search-relevance/pull/151, cherry picked from commit 4b096bbee3022b7e9da7738a0199633ba1315df3

[Upport main] Reformatted release notes according to OS stadard schema (#151)

---

src/test/java/org/opensearch/searchrelevance/action/experiments/ExperimentIT.java

Use admin http client for scenarios when we accessing protected/secured index `.plugins-search-relevance-experiment`, this should fix the failed tests runs when security is enabled in OpenSearch cluster. Example of such failed run in distribution CI: https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test/detail/integ-test/9907/pipeline/135
N/A

Changed http client to secured/admin for cases when we work with protected indexes

---

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/dao/JudgmentCacheDao.java
src/main/java/org/opensearch/searchrelevance/executors/JudgmentResponseProcessor.java
src/main/java/org/opensearch/searchrelevance/executors/JudgmentTaskContext.java
src/main/java/org/opensearch/searchrelevance/executors/LlmJudgmentTaskManager.java
src/main/java/org/opensearch/searchrelevance/indices/SearchRelevanceIndicesManager.java
src/main/java/org/opensearch/searchrelevance/judgments/JudgmentDataTransformer.java
src/main/java/org/opensearch/searchrelevance/judgments/JudgmentsProcessorFactory.java
src/main/java/org/opensearch/searchrelevance/judgments/LlmJudgmentsProcessor.java
src/main/java/org/opensearch/searchrelevance/ml/ChunkProcessingContext.java
src/main/java/org/opensearch/searchrelevance/ml/ChunkResult.java
src/main/java/org/opensearch/searchrelevance/ml/MLAccessor.java
src/main/java/org/opensearch/searchrelevance/ml/MLInputOutputTransformer.java
src/main/java/org/opensearch/searchrelevance/model/JudgmentBatchStatus.java
src/test/java/org/opensearch/searchrelevance/executors/JudgmentDataTransformerTests.java
src/test/java/org/opensearch/searchrelevance/executors/JudgmentResponseProcessorTests.java
src/test/java/org/opensearch/searchrelevance/executors/JudgmentTaskContextTests.java
src/test/java/org/opensearch/searchrelevance/ml/ChunkProcessingContextTests.java

According to RFC 159, implementing task scheduler methods can significantly improve the efficiency of LLM judgment processing. 
LLM Judgments, current issues starting from class LlmJudgmentsProcessor:
- Sequential processing of multiple queries in generateLLMJudgments()
- Blocking search operations across multiple search configurations
- Sequential LLM prediction calls with actionGet() blocking patterns
- Cache lookups performed sequentially per document
> Sequential processing of multiple queries :white_check_mark:
- LlmJudgmentTaskManager with concurrent processing
- queries processed in parallel with semaphore-based rate limiting
> Blocking search operations :white_check_mark:
- Search operations are now asynchronous within each task
- No more sequential blocking across search …

introduce task scheduler to create LLM judgment as batches

---

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/exception/SearchRelevanceException.java
src/main/java/org/opensearch/searchrelevance/rest/RestCreateQuerySetAction.java
src/main/java/org/opensearch/searchrelevance/rest/RestPutExperimentAction.java
src/main/java/org/opensearch/searchrelevance/rest/RestPutJudgmentAction.java
src/main/java/org/opensearch/searchrelevance/rest/RestPutQuerySetAction.java
src/main/java/org/opensearch/searchrelevance/rest/RestPutSearchConfigurationAction.java
src/test/java/org/opensearch/searchrelevance/rest/RestDeleteQuerySetActionTests.java
src/test/java/org/opensearch/searchrelevance/rest/RestDeleteSearchConfigurationActionTests.java
src/test/java/org/opensearch/searchrelevance/rest/RestPutJudgmentActionTests.java

We are seeing a 500 Server Error when creating a Query Set Comparison experiment when the same Search Configuration is provided twice as a parameter. 
**REQUEST**
```
POST /api/relevancy/experiments HTTP/1.1
Host: opense-clust-ibvwxkd20qqp-bb13c7635827b15a.elb.us-east-1.amazonaws.com:8443
Content-Length: 198
osd-version: 3.1.0
Accept-Language: en-US,en;q=0.9
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36
Content-Type: application/json
osd-xsrf: osd-fetch
Accept: */*
Origin: http://opense-clust-ibvwxkd20qqp-bb13c7635827b15a.elb.us-east-1.amazonaws.com:8443/
Referer: http://opense-clust-ibvwxkd20qqp-bb13c7635827b15a.elb.us-east-1.amazonaws.com:8443/app/searchRelevance?security_tenant=__user__
Accept-Encoding: gzip, …
```

bug fix on rest APIs error status for creations

---

.github/workflows/changelog.yml

Replace autocut to dependabot to skip changelog update check
N/A

Replace autocut to dependabot to skip changelog update check

---

src/main/java/org/opensearch/searchrelevance/metrics/MetricsHelper.java
src/main/java/org/opensearch/searchrelevance/model/EvaluationResult.java

The following PR: https://github.com/opensearch-project/search-relevance/pull/174 changes the signature in MetricsHelper which later was added in a test causing a compilation error.
This PR undoes the changes in MetricsHelper fixing the compilation issue. Removing the changes from MetricsHelper is not a problem because this code is no longer used for metrics calculations.

Revert dashboard fields changes of PR#190 to MetricsHelper.

---

.github/workflows/CI.yml
.github/workflows/test_security.yml
CHANGELOG.md
DEVELOPER_GUIDE.md
gradle/wrapper/gradle-wrapper.properties
src/main/plugin-metadata/plugin-security.policy

Updated gradle and java version to 24. 
Request for all plugins from infra team, prereq for 3.2 release. Follow path of other plugins (e.g. https://github.com/opensearch-project/k-NN/pull/2792)

Upgrade gradle to 8.14 and JDK 23->24

---

CHANGELOG.md
src/main/java/org/opensearch/searchrelevance/rest/RestPutJudgmentAction.java
src/main/java/org/opensearch/searchrelevance/rest/RestPutQuerySetAction.java
src/main/java/org/opensearch/searchrelevance/rest/RestPutSearchConfigurationAction.java
src/main/java/org/opensearch/searchrelevance/utils/TextValidationUtil.java
src/test/java/org/opensearch/searchrelevance/rest/RestPutQuerySetActionTests.java
src/test/java/org/opensearch/searchrelevance/rest/RestPutSearchConfigurationActionTests.java
src/test/java/org/opensearch/searchrelevance/util/TextValidationUtilTests.java

- Add text validation for queryText and referenceAnswer when creating query set with manual input. The validation includes json parsing validation and a length check:
- name validation max 50 characters (aligned with frontend check)
- description validation max 250 characters (aligned with frontend check)
- queryText and referenceAnswer validation max 2000 characters
- https://github.com/opensearch-project/search-relevance/issues/186

add queryText and referenceAnswer text validation from manual input

---

src/main/java/org/opensearch/searchrelevance/transport/experiment/PutExperimentTransportAction.java
src/test/java/org/opensearch/searchrelevance/transport/experiment/PutExperimentTransportActionTests.java

- Add empty check for queryTexts to avoid experiment status stuck at "PROCESSING"
- #193 

bug fix for experiment stuck at "PROCESSING" status

---

src/test/java/org/opensearch/searchrelevance/experiment/BaseExperimentIT.java

There is a transmission errors for integration tests. 
```
Suite: Test class org.opensearch.searchrelevance.experiment.HybridOptimizerExperimentIT
Aug 06, 2025 8:07:48 PM org.opensearch.client.RestClient logResponse
WARNING: request [GET http://localhost:9200/.plugins-search-relevance-experiment/_doc/c5e9bcc4-b899-4b60-a44f-7e2b7c7a6f80] returned 1 warnings: [299 OpenSearch-3.2.0-c01ff891fa2d028f79dc20d122ccf16622246856 "this request accesses system indices: [.plugins-search-relevance-experiment], but in a future major version, direct access to system indices will be prevented by default"]
REPRODUCE WITH: ./gradlew ':integTestRemote' --tests 'org.opensearch.searchrelevance.experiment.HybridOptimizerExperimentIT.testHybridOptimizerExperiment_whenHybridQueries_thenSuccessful' …
```

double retries due to transmission errors

---

.github/workflows/delete_backport_branch.yml

This PR verifies that the delete_backport_branch workflow is correctly set up with the actions/github-script@v7 action and proper permissions. The workflow is already configured to delete both 'backport/' and 'release-chores/' branches after they are merged.

Add delete_backport_branch workflow is correctly set up
